<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttendancedataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendancedataRepository extends EntityRepository
{

	public function getAll()
	{
		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->orderBy('a.name', 'DESC')
		->getQuery()
		->getResult()
		;
		return $qb;
	}


	public function getDate($year, $month)
	{
		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->where("a.year = '" . $year . "' AND a.month = '" . $month . "'")
		->orderBy('a.id', 'DESC')
		->getQuery()
		->getResult()
		;
		return $qb;
	}
}