services:
    se_zest.doctrine.notification:
        class: SE\ZestBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    se_zest.validator.antiflood:                              # Le nom du service
        class: SE\ZestBundle\Validator\AntifloodValidator     # La classe du service, ici notre validateur déjà créé
        arguments: [@request_stack, @doctrine.orm.entity_manager] # Les données qu'on injecte au service : la requête et l'EntityManager
        tags:
            - { name: validator.constraint_validator, alias: se_zest_antiflood }  # C'est avec l'alias qu'on retrouvera le service