services:
    se_zest.doctrine.notification:
        class: SE\ZestBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
