se_transfer_homepage:
    path:     /
    defaults: { _controller: SETransferBundle:Transfer:index }
    
se_transfer_add:
    path:     /add
    defaults: { _controller: SETransferBundle:Transfer:addTransfer }
    