se_transfer_homepage:
    path:     /
    defaults: { _controller: SETransferBundle:Transfer:index }
    
se_transfer_history:
    path:     /history
    defaults: { _controller: SETransferBundle:Transfer:history }
    
se_transfer_employees:
    path:     /employees
    defaults: { _controller: SETransferBundle:Transfer:employees }
    
se_transfer_add:
    path:     /add
    defaults: { _controller: SETransferBundle:Transfer:addTransfer }
    
se_transfer_accept:
    path:     /accept/{transfer_id}
    defaults: { _controller: SETransferBundle:Transfer:accept }
    requirements:
        id:  \d+
        
se_transfer_refuse:
    path:     /refuse/{transfer_id}
    defaults: { _controller: SETransferBundle:Transfer:refuse }
    requirements:
        id:  \d+
    