se_admin_index:
    path:     /
    defaults: { _controller: SEAdminBundle:Admin:index }

se_admin_editor:
    path:     /editor
    defaults: { _controller: SEAdminBundle:Editor:editor }

se_admin_import_sap:
    path:     /import
    defaults: { _controller: SEAdminBundle:Import:sap }

se_admin_editor_currentEntry:
    pattern:  /editor/currentEntry
    defaults: { _controller: SEAdminBundle:Editor:currentEntry }
    requirements:
        _method:  GET
