se_report_home:
    path:     /
    defaults: { _controller: SEReportBundle:Productivity:index }

se_report_refresh:
    path:  /refresh
    defaults: { _controller: SEReportBundle:Productivity:refresh }

se_report_hr:
    path:  /hr
    defaults: { _controller: SEReportBundle:Attendance:hr }

se_report_employee_attendance:
    pattern:  /hr/data
    defaults: { _controller: SEReportBundle:Attendance:attendance }
    requirements:
        _method:  GET

se_report_monthly:
    pattern:  /monthly/data
    defaults: { _controller: SEReportBundle:Productivity:monthly }
    requirements:
        _method:  GET

se_report_daily:
    path:  /daily
    defaults: { _controller: SEReportBundle:Productivity:daily }

se_report_day:
    pattern:  /daily/data
    defaults: { _controller: SEReportBundle:Productivity:day }
    requirements:
        _method:  GET