se_report_home:
    path:     /
    defaults: { _controller: SEReportBundle:Productivity:index }

se_report_refresh:
    path:  /refresh
    defaults: { _controller: SEReportBundle:Productivity:refresh }

se_report_hr:
    path:  /hr
    defaults: { _controller: SEReportBundle:Attendance:hr }

se_report_attendance:
    pattern:  /hr/data
    defaults: { _controller: SEReportBundle:Attendance:attendance }
    requirements:
        _method:  GET