login:
    prefix:   /login
    defaults: { _controller: SEUserBundle:Security:login }

login_check:
    prefix:   /login_check

logout:
    prefix:   /logout

se_admin:
    resource: "@SEAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

se_report:
    resource: "@SEReportBundle/Resources/config/routing.yml"
    prefix:   /report

se_input:
    resource: "@SEInputBundle/Resources/config/routing.yml"
    prefix:   /
