se_admin:
    resource: "@SEAdminBundle/Resources/config/routing.yml"
    prefix:   /makan

se_report:
    resource: "@SEReportBundle/Resources/config/routing.yml"
    prefix:   /report

se_input:
    resource: "@SEInputBundle/Resources/config/routing.yml"
    prefix:   /
