se_input_home:
    path:     /input
    defaults: { _controller: SEInputBundle:Entry:input }

se_input_employees:
    path:     /input/employees
    defaults: { _controller: SEInputBundle:Settings:employees }

se_input_employees_add:
    path:     /input/employees/add
    defaults: { _controller: SEInputBundle:Settings:employees_add }

se_input_activities:
    path:     /input/activities
    defaults: { _controller: SEInputBundle:Settings:activities }

se_input_activities_add:
    path:     /input/activities/add
    defaults: { _controller: SEInputBundle:Settings:activities_add }

se_input_import_sap:
    path:     /input/import
    defaults: { _controller: SEInputBundle:Import:sap }

se_input_set_import:
    path:     /input/extimport
    defaults: { _controller: SEInputBundle:Import:set }

se_input_welcome:
    path:     /
    defaults: { _controller: SEInputBundle:Entry:welcome }

se_input_review:
    path:     /review
    defaults: { _controller: SEInputBundle:Dashboard:review }

se_input_ignore:
    pattern:  /review/input/ignore
    defaults: { _controller: SEInputBundle:Dashboard:ignore }
    requirements:
        _method:  POST

se_input_delete:
    pattern:  /review/input/delete
    defaults: { _controller: SEInputBundle:Dashboard:delete }
    requirements:
        _method:  POST

se_input_populate:
    pattern:  /input/populate
    defaults: { _controller: SEInputBundle:Entry:populate }
    requirements:
        _method:  GET

se_input_review_details:
    path:     /review/{id}
    defaults: { _controller: SEInputBundle:Dashboard:reviewDetails }
    requirements:
        id:   \d+

se_input_review_activities:
    pattern:  /review/activities
    defaults: { _controller: SEInputBundle:Dashboard:activities }
    requirements:
        _method:  GET

se_input_review_mi:
    pattern:  /review/mi
    defaults: { _controller: SEInputBundle:Dashboard:missingInput }
    requirements:
        _method:  GET

se_input_review_time:
    pattern:  /review/time
    defaults: { _controller: SEInputBundle:Dashboard:timeReview }
    requirements:
        _method:  GET

se_input_review_edit_new:
    pattern:  /edit/new
    defaults: { _controller: SEInputBundle:Dashboard:editNew }
    requirements:
        _method:  POST

se_input_review_edit_modify:
    pattern:  /edit/modify
    defaults: { _controller: SEInputBundle:Dashboard:editModify }
    requirements:
        _method:  POST

se_input_review_edit_delete:
    pattern:  /edit/delete
    defaults: { _controller: SEInputBundle:Dashboard:editDelete }
    requirements:
        _method:  POST

se_input_review_edit:
    pattern:  review/edit
    defaults: { _controller: SEInputBundle:Dashboard:editor }
    requirements:
        _method:  POST